### PR TITLE
Only one Autoexec.ash + some fixes

### PR DESCRIPTION
**Pull request by shayanb**
- Screenshot added
- To Do list

### CODE REVIEW

**Comment by KonradIT** [comment]
@shayanb hi. The day after I pushed the first commit i didn't get to work the mount command, I am sure index.html is in a because I have listed it using autiexec.ash and telnet.

Did the mount worked for you in the second try? I cant get mount to work, I will update my camera.

So it mounts to live dir, we need to make another dir in /var/www/ called "control", the folder is writeproof. Also, have a look at this gist: https://gist.github.com/KonradIT/99d887210dec002111e1

The last one, start_preview its interesting, live its only a mirror, so if I can create a dir in /tmp/fuse named control and with start preview mount it thats all.

Man, thanks for this pr, I will do the preview part and the txt parsing part.

**Comment by shayanb** [comment]
This script that I included in this pull works fine on my GoPro 3Plus Black on every reboot.

and btw some settings does not work on the 3Plus black. I'll send you an email with some detail

**Comment by KonradIT** [comment]
@shayanb I need you to sniff the com between your GoPro and the computer, the reason some settings do not work is because i dont own a 3+ black, i own the black. So a hero3+black user gave me the commands.

To sniff the communication, you will need Wireshark. Now, being a security researcher you must have done this already: connect the gopro to your mac and phone, in the phone start the gopro app and control your camera. In your mac open wireshark and capture the wlan. I need specifically these settings:
- Protune: Exposure settings
- Protune: Color
- Protune: ISO limit
- Protune: Sharpness

Please mail me the commands, or pull them directly to the index.html file.

Also, please test all the commands.

---

When mounting the gopro controller, we have no live preview because its mounted to the live directory, so perhaps before mounting fuse_a run this? 

```
mount --bind /tmp/fuse/shutter /var/www/shutter
```

I got it from usr/local/gopro/scripts/[start_preview.sh](https://gist.github.com/KonradIT/99d887210dec002111e1#file-start_preview-sh)

Also, when the gopro has live and videos without the gopro controller we can make it permanent (without autoexec.ash) using tcp_tuner.sh

And... to read the states from the GoPro I wrote this: http://codepen.io/KonradIT/pen/nacqj

**Comment by KonradIT** [comment]
Problem: livestream is cancelled because the controller is mounted in live, the livestream directory.

Solution:

**Pull request merged**
